name: Migration
main: gg.uhc.migration.Entry
version: 1.0.0
author: ghowden/Eluinhost
database: false
depend: []
commands:
  migration:
    description: stops/starts migration tasks
permissions:
  uhc.migration:
    description: Allows use of the /migration command
    default: op